<?php

	$BASEURL="https://sandbox.about2pay.com/";
	$BASIC="YWQ5NzQ1OGItMGU3Ny00MWQzLWIwNTMtZTI4ZDVmYmUxNTZhOmYyZTU3ZmU5LTFjYjAtNGJjNC1hYjQzLWE2NWE4NzI0YmRjZA==";
	//$BASIC_CHIPS='MDk1MjAxMjktOGZkZS00ODg2LThhNWItZThiMWQxOTYxM2EwOjE5OTcyMmU4LWZkZjYtNDljYy1iMmZkLTdlYmYyNWM4OTIyYw==';
	$BASIC_CHIPS='Q01NLWNoYW5uZWwtdXVpZC0wMDAwMDAwMDAwMDAwMDAwMDAxOkNNTS1zZWNyZXQtMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMQ==';
	$BASIC_TRIDENT='OGI1Y2IxYTItNDAzNi00ZWUyLWE2ZGItMTM5ZmY3NWYwMzdkOjNhYzhlNGFiLTk1ZWUtNDg3ZC1iNGM4LWQxYjFiY2FmNzhlOA==';
	//$BASIC_CHIPS='Q01NLWNoYW5uZWwtMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxOkNNTS1zZWNyZXQtMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMQ==';
	$TARAPI='https://tar.sandbox.tlsag.net/api/v1.0/';
	$ECOMAPI='https://tar.sandbox.tlsag.net/api/v1.0/ecom/';
	$IVERIID='{EAC5A1E6-0889-48C4-8936-3247ABF630B2}';

  /*$BASEURL="https://instapay-prod.azurewebsites.net/";
  $BASIC="NzY5YzkyYmYtYzcyNS00MTRmLTk3NDItY2M4YjVhNzhhODFmOjM0MjYzYzgxLTU3ZTUtNDUyZS1iZmRiLWY2NzJlYWE0MGJmZg==";
  //$BASIC_CHIPS='YWM2ODlmYTUtZjdkMC00NzYwLThjODQtMWYxNjkyZmZkODE3OmE3Nzc2NzE5LWJkNTEtNDdkNS05ZDYzLTY3MDIyZWEzNDhkNQ==';
  $BASIC_CHIPS='Q01NLWNoYW5uZWwtMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxOkNNTS1zZWNyZXQtMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMQ==';
  $TARAPI='https://tar.tlsag.net/api/v1.0/';
  $ECOMAPI='https://tar.tlsag.net/api/v1.0/ecom/';
  $IVERIID='{EAC5A1E6-0889-48C4-8936-3247ABF630B2}';*/



?>
